---
title: "s-pearson-final-project"
author: "Sophia Pearson"
date: "12/10/2021"
output:
  html_document:
    highlight: kate
    code_folding: show
    theme: cosmo
    df_print: paged
    toc: true
    toc_depth: 6
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(janitor)
library(rmarkdown)
base::options(
  tibble.print_max = 25,
  tibble.width = 78,
  scipen = 100000000,
  max.print = 999999
)
knitr::opts_chunk$set(
  echo = TRUE, # show/hide all code
  # results = "hide", # hide/show results
  tidy = FALSE, # cleaner code printing
  comment = "#", # better console printing
  eval = TRUE, # turn this to FALSE stop code chunks from running
  message = TRUE, # show messages
  fig.width = 7, # figure width
  fig.height = 5, # figure height
  warning = FALSE, # show warnings
  size = "small", # size of the text
  fig.path = "img/" # location of figures
)
knitr::opts_knit$set(
  width = 78
)
```

## Import

```{r}
movies <- readr::read_csv(file = "data/raw/imdb-movies.csv")
```

## Summary Statistics

```{r}
skimr::skim(movies)
```
## Single Variable Graphs

### Histogram

```{r}
labs_hist <- labs(title = "Histogram of Critics Score", 
                  x = "Critics Score")
movies %>% 
  ggplot(aes(x = critics_score)) + 
    geom_histogram() + 
      labs_hist
```


### Frequency Polygon

```{r}
labs_freq <- labs(title = "Frequency polygon of Critics Score", 
                  x = "Critics Score")
movies %>% 
  ggplot(aes(x = critics_score)) + 
    geom_freqpoly() + 
      labs_freq
```



## Multiple Variable Graphs


### Boxplots

```{r boxplot} 
labs_box <- labs(
     title = "Critics Score by Genre",
     subtitle = "source: https://github.com/hadley/data-movies",
     fill = "Genre",
     x = "Critics Score",
     y = "Genre")
movies %>%  
  filter(!is.na(genre)) %>% 
  ggplot() + 
  geom_boxplot(aes(x = critics_score, 
                      y = genre, 
                      fill = genre),
                      alpha = 1/5, 
               show.legend = FALSE) + 
  labs_box
```




